DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	UID SERIAL PRIMARY KEY, 
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL
);

INSERT INTO USERS (EMAIL, PASSWORD) VALUES
('one@fbi.com', 'me'),
('t2@fbi.com', 'there'),
('waw@fbi.com', 'exactly');

SELECT * FROM USERS;